# Generated by Django 3.1.5 on 2021-01-11 03:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_trip', models.ImageField(upload_to='img_trip/', verbose_name='Картинка')),
                ('title', models.TextField(max_length=1000, verbose_name='Наименование тура')),
                ('description', ckeditor.fields.RichTextField(max_length=3000, verbose_name='Описание тура')),
                ('date_start', models.DateField(verbose_name='Дата начала тура')),
                ('date_end', models.DateField(verbose_name='Дата окончания тура')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='Цена')),
                ('included_coast', ckeditor.fields.RichTextField(verbose_name='В стоимость включено')),
                ('not_included_coast', ckeditor.fields.RichTextField(verbose_name='В стоимость не включено')),
                ('number_party', models.PositiveIntegerField(null=True, verbose_name='Количество участников')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
            },
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='День №')),
                ('description', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Описание дня')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roadmap_trip', to='trips.trip', verbose_name='Дорожная карта')),
            ],
            options={
                'verbose_name': 'Дорожная карта',
                'verbose_name_plural': 'Дорожные карты',
            },
        ),
    ]
