# Generated by Django 3.1.5 on 2021-01-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя автора тура')),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='img_trip',
            field=models.ImageField(upload_to='img_trip/', verbose_name='Изображение тура'),
        ),
    ]
