# Generated by Django 3.1.5 on 2021-01-11 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20210111_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_author', to='trips.tourauthor', verbose_name='Автор тура'),
        ),
    ]
