# Generated by Django 3.1.5 on 2021-01-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20210111_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourauthor',
            options={'verbose_name': 'Автор тура', 'verbose_name_plural': 'Авторы туров'},
        ),
        migrations.AddField(
            model_name='tourauthor',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roadmap_trip', to='trips.trip', verbose_name='Дорожная карта путешествия'),
        ),
    ]
