# Generated by Django 3.1.5 on 2021-02-15 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_registration_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
